### ISSUE TITLE
Job fails with PDOException: SQLSTATE[HY000]: General error: -902 connection shutdown

### ISSUE THREAD

**Issue by qwasyx0** [harrygulliford/laravel-firebird#30]
Hello, I have been encoutering this behavior for couple months now. Basically, I have a job that makes connection to firebird, selects or inserts in table. Like every 2nd job instantly fails. The job is very simple:

```php
    /**
     * Execute the job.
     *
     * @return void
     */
    public function handle()
    {
        A_REPORT_MAILY::create($this->data);
    }
```

$this->data:
```
SQL: insert into "A_REPORT_MAILY" ("IDCISELPOD_UZIV_WEB", "ODESILATEL", "ADRESAT", "DATUMCAS", "PREDMET", "TELO", "TYP") values (18,mail@mail.com, othermail@mail.com, 2022-06-08 16:26:13, Objednávka servisu stroje BT HWE 100, {"Firma:":"Auto SAS s.r.o.","N\u00e1zev stroje:":"BT HWE 100","V\u00fdrobn\u00ed \u010d\u00edslo:":"6443726","Eviden\u010dn\u00ed \u010d\u00edslo:":"S314","Nepoj\u00edzdn\u00fd:":"N","P\u0159es\u010das:":"N","Vypracovat cenovou nab\u00eddku:":"N","STK:":"N","Emise:":"N","TK:":"N","LPG\/CNG:":"N","Regenerace baterie:":"N","Revize plo\u0161iny:":"N","\u00dadr\u017eba - servis:":"A","Z\u00e1vada:":"N","Popis z\u00e1vady:":"Pros\u00edm o proveden\u00ed \u00fadr\u017eby stroje - po domluv\u011b s p.Toch\u00e1\u010dkem zkus\u00edme napl\u00e1novat i regeneraci bateri\u00ed. \nMF","\u010cas objedn\u00e1vky:":"08.06.2022 16:26"}, 1))
```
Payload:
```json
{"uuid":"699332c6-b8c7-43a1-b78a-1572a706c40d","timeout":null,"id":"0bCGBJ9T5NxopF7BvcT3gxC5JfU3tPWN","backoff":null,"displayName":"App\\Jobs\\VytvorSouhrnnyReportJob","maxTries":null,"failOnTimeout":false,"maxExceptions":null,"retryUntil":null,"job":"Illuminate\\Queue\\CallQueuedHandler@call","data":{"command":"O:32:\"App\\Jobs\\VytvorSouhrnnyReportJob\":10:{s:3:\"job\";N;s:10:\"connection\";N;s:5:\"queue\";N;s:15:\"chainConnection\";N;s:10:\"chainQueue\";N;s:19:\"chainCatchCallbacks\";N;s:5:\"delay\";N;s:11:\"afterCommit\";N;s:10:\"middleware\";a:0:{}s:7:\"chained\";a:0:{}}","commandName":"App\\Jobs\\VytvorSouhrnnyReportJob"},"attempts":2}
```

Exception:
```stacktrace
PDOException: SQLSTATE[HY000]: General error: -902 connection shutdown  in /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:368
Stack trace:
#0 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(368): PDO->prepare()
#1 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(709): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#2 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(676): Illuminate\Database\Connection->runQueryCallback()
#3 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#4 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2556): Illuminate\Database\Connection->select()
#5 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2544): Illuminate\Database\Query\Builder->runSelect()
#6 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3078): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#7 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2545): Illuminate\Database\Query\Builder->onceWithColumns()
#8 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(675): Illuminate\Database\Query\Builder->get()
#9 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(659): Illuminate\Database\Eloquent\Builder->getModels()
#10 /www/hosting/sas-report.cz/www/app/Jobs/VytvorSouhrnnyReportJob.php(40): Illuminate\Database\Eloquent\Builder->get()
#11 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): App\Jobs\VytvorSouhrnnyReportJob->App\Jobs\{closure}()
#12 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(453): Illuminate\Database\Connection->transaction()
#13 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Database\DatabaseManager->__call()
#14 /www/hosting/sas-report.cz/www/app/Jobs/VytvorSouhrnnyReportJob.php(42): Illuminate\Support\Facades\Facade::__callStatic()
#15 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\VytvorSouhrnnyReportJob->handle()
#16 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#17 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#18 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#19 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#20 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#21 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#22 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#24 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(119): Illuminate\Bus\Dispatcher->dispatchNow()
#25 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#26 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(121): Illuminate\Pipeline\Pipeline->then()
#28 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(69): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#29 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#30 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Jobs\Job->fire()
#31 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\Queue\Worker->process()
#32 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\Queue\Worker->runJob()
#33 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(126): Illuminate\Queue\Worker->daemon()
#34 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(110): Illuminate\Queue\Console\WorkCommand->runWorker()
#35 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#36 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#37 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#38 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#39 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#40 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#41 /www/hosting/sas-report.cz/www/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute()
#42 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#43 /www/hosting/sas-report.cz/www/vendor/symfony/console/Application.php(989): Illuminate\Console\Command->run()
#44 /www/hosting/sas-report.cz/www/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#45 /www/hosting/sas-report.cz/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#46 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#47 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#48 /www/hosting/sas-report.cz/www/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#49 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000]: General error: -902 connection shutdown  (SQL: select * from "A_CISELPOD_ODP_OSOBA" where "MAILY_VSE" = A and "MAIL" is not null) in /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php:716
Stack trace:
#0 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(676): Illuminate\Database\Connection->runQueryCallback()
#1 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Connection.php(376): Illuminate\Database\Connection->run()
#2 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2556): Illuminate\Database\Connection->select()
#3 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2544): Illuminate\Database\Query\Builder->runSelect()
#4 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3078): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#5 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2545): Illuminate\Database\Query\Builder->onceWithColumns()
#6 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(675): Illuminate\Database\Query\Builder->get()
#7 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(659): Illuminate\Database\Eloquent\Builder->getModels()
#8 /www/hosting/sas-report.cz/www/app/Jobs/VytvorSouhrnnyReportJob.php(40): Illuminate\Database\Eloquent\Builder->get()
#9 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/Concerns/ManagesTransactions.php(29): App\Jobs\VytvorSouhrnnyReportJob->App\Jobs\{closure}()
#10 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Database/DatabaseManager.php(453): Illuminate\Database\Connection->transaction()
#11 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(337): Illuminate\Database\DatabaseManager->__call()
#12 /www/hosting/sas-report.cz/www/app/Jobs/VytvorSouhrnnyReportJob.php(42): Illuminate\Support\Facades\Facade::__callStatic()
#13 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\VytvorSouhrnnyReportJob->handle()
#14 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#15 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#16 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#17 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#18 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#19 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#20 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#21 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#22 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(119): Illuminate\Bus\Dispatcher->dispatchNow()
#23 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#24 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(121): Illuminate\Pipeline\Pipeline->then()
#26 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(69): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#27 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#28 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(428): Illuminate\Queue\Jobs\Job->fire()
#29 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(378): Illuminate\Queue\Worker->process()
#30 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(172): Illuminate\Queue\Worker->runJob()
#31 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(126): Illuminate\Queue\Worker->daemon()
#32 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(110): Illuminate\Queue\Console\WorkCommand->runWorker()
#33 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\Queue\Console\WorkCommand->handle()
#34 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#35 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#36 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#37 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\Container\BoundMethod::call()
#38 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#39 /www/hosting/sas-report.cz/www/vendor/symfony/console/Command/Command.php(291): Illuminate\Console\Command->execute()
#40 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#41 /www/hosting/sas-report.cz/www/vendor/symfony/console/Application.php(989): Illuminate\Console\Command->run()
#42 /www/hosting/sas-report.cz/www/vendor/symfony/console/Application.php(299): Symfony\Component\Console\Application->doRunCommand()
#43 /www/hosting/sas-report.cz/www/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun()
#44 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Console/Application.php(102): Symfony\Component\Console\Application->run()
#45 /www/hosting/sas-report.cz/www/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#46 /www/hosting/sas-report.cz/www/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#47 {main}
```

Only reference I could find related to php: https://bugs.php.net/bug.php?id=64603&edit=1

Is this a bug with the driver or really a php-firebird issue that can't be fixed here?

**Comment by harrygulliford** [comment]
Could you try setting the pdo attribute PDO::ATTR_PERSISTENT to false on the connection? However, it does appear to be an issue with the pdo driver itself, as that is where the error is being emitted from. I'd also suggest checking that you're on the latest version of PHP and therefore the Firebird PDO driver.
